### ISSUE TITLE
JS is not working for any version of Internet Explorer

### ISSUE THREAD

**Issue by edgarjoao** [basilfx/HTMLFeedback#1]
Hi, I have tested the plugin and is not working for any version of Internet Explorer

**Comment by basilfx** [comment]
Thank you for reporting. I will look into this issue the next few days.

**Comment by basilfx** [comment]
Issue is fixed in latest commit(s). Of course, it was some comma related issue, but I have managed to see it working in IE9 and IE10. Make sure you disable compatibility view.

Sorry for the long delay.
