### ISSUE TITLE
SVG Element not getting capture

### ISSUE THREAD

**Issue by vishal-px** [basilfx/HTMLFeedback#3]
Hi @basilfx 

Thanks for this library it's awesome.
Here, I get one issue with SVG element.
I have done inspect element and paste SVG element and try to capture the page but SVG element not getting captured.

For better understanding please see this [video](https://www.useloom.com/share/e2e14f8deb8046dfaac366e214d078ff)

Is there any solution for this issue?

Thanks.

**Comment by basilfx** [comment]
This library is not under development anymore. You can try to see if a later version of [HTML2Canvas](https://github.com/niklasvh/html2canvas/) solves your problem

**Comment by vishal-px** [comment]
Hi @basilfx Thanks for replay, On latest version SVG Element getting ZOOM see this [issue](https://github.com/niklasvh/html2canvas/issues/1441) .
